name: dolan_yuk
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  http: ^1.1.0
  email_validator: ^2.1.16
  image_picker: ^0.8.6
  numberpicker: ^2.1.2
  percent_indicator: ^4.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
